# Generated by Django 2.1.4 on 2019-01-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcment',
            fields=[
                ('AnnouncmentID', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
