# Generated by Django 2.1.4 on 2019-01-05 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='skillCategory',
        ),
    ]
