# Generated by Django 2.1.4 on 2019-01-06 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('serviceTypeID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shiftID', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('startTime', models.TimeField()),
                ('endDate', models.DateField()),
                ('hours', models.IntegerField(default=0)),
                ('placesAvailable', models.IntegerField(default=0)),
                ('placesFilled', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Service')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftType',
            fields=[
                ('shiftTyepID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Shift')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='shiftType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.ShiftType'),
        ),
        migrations.AddField(
            model_name='service',
            name='serviceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.ServiceType'),
        ),
    ]
