# Generated by Django 2.1.4 on 2019-01-05 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='skill',
            fields=[
                ('skillID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('attemptsRequired', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='skillCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.skillCategory'),
        ),
    ]
