# Generated by Django 2.1.4 on 2019-01-05 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shifts', '0001_initial'),
        ('skill', '0002_auto_20190105_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillPerformed',
            fields=[
                ('skillPerformedID', models.AutoField(primary_key=True, serialize=False)),
                ('supervisor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('comment', models.TextField(null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shifts.Service')),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.SkillCategory'),
        ),
        migrations.AddField(
            model_name='skillperformed',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill.Skill'),
        ),
        migrations.AddField(
            model_name='skillperformed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
